/**
 * MockFeedbackService — Simulates Supabase Edge Functions + Gemini 1.5 Flash
 *
 * Preserves current prototype behavior:
 * - analyzeFeedback: Returns hardcoded strengths + opportunities after ~3s analyzing screen
 * - generateImprovedScript: Returns hardcoded script sections after ~3s analyzing screen
 * - generateResultsSummary: Returns hardcoded pronunciation tips + improvement areas
 *
 * Error simulation (when ?simulate_errors=true):
 * - analyzeFeedback → FeedbackError("ANALYSIS_FAILED")
 * - generateImprovedScript → FeedbackError("SCRIPT_GENERATION_FAILED")
 * - generateResultsSummary → FeedbackError("SUMMARY_FAILED")
 */
import type { IFeedbackService } from "../../interfaces";
import type { SessionFeedbackResult, ImprovedScriptResult, CompletedPhraseSummary, ResultsSummary } from "../../types";
import { FeedbackError } from "../../errors";
import { MOCK_STRENGTHS, MOCK_OPPORTUNITIES } from "./data/feedback-data";
import { MOCK_SCRIPT_SECTIONS } from "./data/script-sections";
import { getScriptSectionsForScenario } from "./data/script-sections-by-scenario";
import { MOCK_COMPLETED_PHRASES } from "./data/completed-phrases";
import {
  MOCK_OVERALL_SENTIMENT,
  MOCK_PRONUNCIATION_NOTES,
  MOCK_IMPROVEMENT_AREAS,
} from "./data/results-summary-data";
import { delay, shouldSimulateError } from "./utils";

export class MockFeedbackService implements IFeedbackService {
  async analyzeFeedback(_sessionId: string): Promise<SessionFeedbackResult> {
    // The analyzing screen in the prototype runs for ~3s (handled by AnalyzingScreen component)
    // This service just returns the data; the UI manages the loading animation
    await delay(500);

    /* ── Error simulation ── */
    if (shouldSimulateError("feedback")) {
      throw new FeedbackError("ANALYSIS_FAILED");
    }

    return {
      strengths: [...MOCK_STRENGTHS],
      opportunities: [...MOCK_OPPORTUNITIES],
      duration: "12 minutos",
      scenarioType: "Sales pitch",
    };
  }

  async generateImprovedScript(
    _sessionId: string
  ): Promise<ImprovedScriptResult> {
    // Same as above — AnalyzingScreen manages the visual delay
    await delay(500);

    /* ── Error simulation ── */
    if (shouldSimulateError("feedback")) {
      throw new FeedbackError("SCRIPT_GENERATION_FAILED");
    }

    return {
      sections: MOCK_SCRIPT_SECTIONS.map((s) => ({ ...s })),
      estimatedReadTime: "2 min 30 seg",
    };
  }

  async getCompletedSummary(
    _sessionId: string
  ): Promise<CompletedPhraseSummary[]> {
    await delay(300);

    /* ── Error simulation ── */
    if (shouldSimulateError("feedback")) {
      throw new FeedbackError("SUMMARY_FAILED");
    }

    return MOCK_COMPLETED_PHRASES.map((p) => ({ ...p }));
  }

  async generateResultsSummary(
    _sessionId: string
  ): Promise<ResultsSummary> {
    // Simulates Gemini Flash generating pronunciation tips
    // + Edge Function computing totalPhrases/totalTime from session metadata
    await delay(400);

    /* ── Error simulation ── */
    if (shouldSimulateError("feedback")) {
      throw new FeedbackError("SUMMARY_FAILED");
    }

    return {
      // Computed by Edge Function (not Gemini)
      totalPhrases: 3,
      totalTime: "4 min",
      // Generated by Gemini
      overallSentiment: MOCK_OVERALL_SENTIMENT,
      pronunciationNotes: MOCK_PRONUNCIATION_NOTES.map((n) => ({ ...n })),
      improvementAreas: MOCK_IMPROVEMENT_AREAS.map((a) => ({ ...a })),
    };
  }
}