/**
 * ══════════════════════════════════════════════════════════════
 *  MasteryTalk PRO — Service Layer: Shared Types
 *
 *  Sprint 2 FSD: domain types live in src/entities/.
 *  This file re-exports them for backward compatibility so all
 *  existing import paths continue to work unchanged.
 * ══════════════════════════════════════════════════════════════
 */

/* ── User & Auth (entities/user) ── */

import type { UserPlan, User, AuthProvider, OnboardingProfile } from "@/entities/user";
export type { UserPlan, User, AuthProvider, OnboardingProfile };

/* ── Session (entities/session) ── */

import type { ScenarioType, ChatMessage, SessionConfig, ArenaPhase, ArenaPowerPhrase, ArenaState } from "@/entities/session";
export type { ScenarioType, ChatMessage, SessionConfig, ArenaPhase, ArenaPowerPhrase, ArenaState };

/* ── Feedback (entities/feedback) ── */

import type {
  SessionSummaryNextStep,
  SessionSummary,
  Strength,
  Opportunity,
  SessionFeedbackResult,
  BeforeAfterComparison,
  ContentQualityScores,
  ContentInsight,
  InterviewReadinessData,
  RealFeedbackData,
  PronunciationCategory,
  PronunciationNote,
  ImprovementArea,
} from "@/entities/feedback";
export type {
  SessionSummaryNextStep,
  SessionSummary,
  Strength,
  Opportunity,
  SessionFeedbackResult,
  BeforeAfterComparison,
  ContentQualityScores,
  ContentInsight,
  InterviewReadinessData,
  RealFeedbackData,
  PronunciationCategory,
  PronunciationNote,
  ImprovementArea,
};

/* ── Progression (entities/progression) ── */

import type {
  LevelStatus,
  LevelState,
  ProgressionState,
  PathStatus,
  PathLevelProgress,
  PathLevelAccess,
  RemedialLesson,
  RemedialShadowingPhrase,
  RemedialContent,
  LessonConceptStep,
  LessonScenarioStep,
  LessonComparisonStep,
  LessonToolkitPhrase,
  LessonToolkitStep,
  LessonExerciseStep,
  LessonStep,
  StructuredLesson,
} from "@/entities/progression";
export type {
  LevelStatus,
  LevelState,
  ProgressionState,
  PathStatus,
  PathLevelProgress,
  PathLevelAccess,
  RemedialLesson,
  RemedialShadowingPhrase,
  RemedialContent,
  LessonConceptStep,
  LessonScenarioStep,
  LessonComparisonStep,
  LessonToolkitPhrase,
  LessonToolkitStep,
  LessonExerciseStep,
  LessonStep,
  StructuredLesson,
};

/* ── Payment (entities/payment) ── */

import type { PurchaseType, PurchaseDetails, CheckoutResult, PathAccessInfo, CreditPack, SubscriptionInfo } from "@/entities/payment";
import { PATH_PRODUCTS, CREDIT_PACK_DETAILS } from "@/entities/payment";
export type { PurchaseType, PurchaseDetails, CheckoutResult, PathAccessInfo, CreditPack, SubscriptionInfo };
export { PATH_PRODUCTS, CREDIT_PACK_DETAILS };

/* ── Session & Conversation (service output types — stay here) ── */

export interface PreparedSession {
  sessionId: string;
  systemPrompt: string;
  firstMessage: ChatMessage;
  voiceId?: string;
}

export interface ConversationTurnResult {
  aiMessage: ChatMessage;
  isComplete: boolean;
  coachingHint?: { starter: string; keywords?: string[]; strategy: string } | null;
}

/* ── Script / Improved Script (service output types — stay here) ── */

export interface ScriptHighlight {
  phrase: string;
  color: string;
  tooltip: string;
}

export interface ScriptParagraph {
  text: string;
  highlights: ScriptHighlight[];
  suffix?: string;
  isHighlightBlock?: boolean;
}

export interface ResponseStep {
  step: string;
  template: string;
}

export interface ScriptSection {
  num: number;
  title: string;
  paragraphs: ScriptParagraph[];
  /** Fill-in-the-blank response scaffold — generated by the backend per key moment */
  responseSteps?: ResponseStep[];
}

export interface ImprovedScriptResult {
  sections: ScriptSection[];
  estimatedReadTime: string;
}

/* ── Interview Briefing (service output types — stay here) ── */

export interface InterviewQuestionCard {
  id: number;
  question: string;
  why: string;
  approach: string;
  suggestedOpener: string;
  /** Full 2-3 sentence example answer using the user's profile data */
  exampleAnswer?: string;
  framework?: { name: string; description: string };
  keyPhrases: ScriptHighlight[];
  pivot: string;
  /** Context-specific fill-in-the-blank response scaffold */
  responseSteps?: ResponseStep[];
}

export interface InterviewQuestionToAsk {
  question: string;
  why: string;
}

export interface InterviewCulturalTip {
  title: string;
  description: string;
  type: "do" | "avoid";
}

export interface InterviewBriefingData {
  anticipatedQuestions: InterviewQuestionCard[];
  questionsToAsk: InterviewQuestionToAsk[];
  culturalTips: InterviewCulturalTip[];
}

/* ── Speech & Pronunciation (service output types — stay here) ── */

export interface TranscriptionResult {
  text: string;
  confidence: number;
}

export interface WordFeedback {
  word: string;
  phonetic: string;
  tip: string;
}

export interface PronunciationResult {
  score: number;
  wordFeedback: WordFeedback;
}

export interface AzurePhonemeAssessment {
  phoneme: string;
  accuracyScore: number;
}

export interface AzureWordAssessment {
  word: string;
  accuracyScore: number;
  errorType: 'None' | 'Mispronunciation' | 'Omission' | 'Insertion';
  phonemes: AzurePhonemeAssessment[];
}

export interface AzurePronunciationAssessment {
  accuracyScore: number;
  fluencyScore: number;
  completenessScore: number;
  prosodyScore: number;
  pronScore: number;
  words: AzureWordAssessment[];
  recognizedText: string;
  wordCount: number;
  problemWordCount: number;
}

export interface SessionPronunciationData {
  turns: TurnPronunciationData[];
  sessionAccuracy: number;
  sessionFluency: number;
  sessionProsody: number;
}

export interface TurnPronunciationData {
  turnIndex: number;
  assessment: AzurePronunciationAssessment;
  timestamp: string;
}

export interface PracticePhrase {
  id: string;
  phrase: string;
  context: string;
  overallScore: number;
  problemWords: {
    word: string;
    score: number;
    commonMistake: string;
  }[];
}

export interface FluencyInsight {
  speechRate: number;
  targetRate: [number, number];
  hesitationPauses: number;
  hesitationTriggers: string[];
  tip: string;
}

export interface VocabPronunciationEntry {
  word: string;
  category: 'Technical' | 'Business' | 'Leadership' | 'Communication';
  totalAttempts: number;
  scores: number[];
  currentScore: number;
  trend: 'improving' | 'stable' | 'declining';
  mastery: 'learning' | 'practicing' | 'mastered';
  commonError?: string;
  lastPracticed: string;
}

export interface ResultsSummary {
  totalPhrases: number;
  totalTime: string;
  overallSentiment: string;
  pronunciationNotes: PronunciationNote[];
  improvementAreas: ImprovementArea[];
}

/* ── Shadowing (service output types — stay here) ── */

export interface ShadowingPhrase {
  text: string;
  feedback: WordFeedback;
  scores: number[];
}

/* ── Spaced Repetition (service implementation — stays here) ── */

export interface SRCard {
  id: string;
  phrase: string;
  word: string;
  phonetic: string;
  lastScore: number;
  intervalStep: number;
  origin: string;
  nextReviewDate?: string;
}

export interface SRInterval {
  step: number;
  days: number;
  label: string;
}

export interface SRSessionResult {
  cardId: string;
  score: number;
  passed: boolean;
  nextInterval: string;
}

/* ── Practice History (stay here — dashboard-specific) ── */

export interface PracticeHistoryItem {
  title: string;
  date: string;
  duration: string;
  tag: string;
  arenaPhaseReached?: ArenaPhase;
  powerPhrasesUsed?: number;
  srCardsPending?: number;
  srCardsMastered?: number;
  beforeAfterHighlight?: BeforeAfterComparison;
}

/* ── Power Phrases ── */

export interface PowerPhrase {
  phrase: string;
  category: string;
  whenToUse: string;
  situation: string;
  accentColor: string;
}

/* ── Completed Phrase Summary ── */

export interface CompletedPhraseSummary {
  num: number;
  text: string;
  highlight: { word: string; phonetic: string } | null;
  suffix: string;
  hasActions: boolean;
}
