/**
 * ══════════════════════════════════════════════════════════════
 *  inFluentia PRO — Service Layer: Shared Types
 *  Models used across all service interfaces and adapters.
 * ══════════════════════════════════════════════════════════════
 */

/* ── User & Auth ── */

export type UserPlan = "free" | "per-session";

export interface User {
  uid: string;
  displayName: string;
  email: string;
  photoURL?: string;
  plan: UserPlan;
  freeSessionUsed: boolean;
  sessionsCompleted: number;
  marketFocus?: "mexico" | "colombia" | "brazil";
  createdAt: string;
}

export type AuthProvider = "google";

/* ── Scenario Types (Master Prompt Adaptation) ── */

export type ScenarioType =
  | "interview"
  | "sales";

/* MVP ships with interview + sales only. Future expansions (csuite, negotiation, networking) were removed from assembler.ts during v2.1 cleanup. */

/* ── Session & Conversation ── */

export interface ChatMessage {
  role: "user" | "ai";
  label?: string;
  time: string;
  text: string;
}

export interface SessionConfig {
  scenario: string;
  interlocutor: string;
  scenarioType?: ScenarioType;
  context?: string;
  /** Guided fields captured in PracticeSetup (varies per scenarioType) */
  guidedFields?: Record<string, string>;
  /** User's market focus (region) for regional prompt adaptation */
  marketFocus?: "mexico" | "colombia" | "brazil" | null;
}

export interface PreparedSession {
  sessionId: string;
  systemPrompt: string;
  firstMessage: ChatMessage;
  /** ElevenLabs voice_id assigned by prepare-session based on interlocutor */
  voiceId?: string;
}

export interface ConversationTurnResult {
  /** AI's response message */
  aiMessage: ChatMessage;
  /** Whether the conversation has naturally concluded */
  isComplete: boolean;
}

/* ── Feedback ── */

export interface Strength {
  title: string;
  desc: string;
}

export interface Opportunity {
  title: string;
  tag?: string;
  desc: string;
}

export interface SessionFeedbackResult {
  strengths: Strength[];
  opportunities: Opportunity[];
  duration: string;
  scenarioType: string;
}

/* ── Improved Script ── */

export interface ScriptHighlight {
  phrase: string;
  color: string;
  tooltip: string;
}

export interface ScriptParagraph {
  text: string;
  highlights: ScriptHighlight[];
  suffix?: string;
  isHighlightBlock?: boolean;
}

export interface ScriptSection {
  num: number;
  title: string;
  paragraphs: ScriptParagraph[];
}

export interface ImprovedScriptResult {
  sections: ScriptSection[];
  estimatedReadTime: string;
}

/* ── Speech & Pronunciation ── */

export interface TranscriptionResult {
  text: string;
  confidence: number;
}

export interface WordFeedback {
  word: string;
  phonetic: string;
  tip: string;
}

export interface PronunciationResult {
  score: number;
  wordFeedback: WordFeedback;
}

/* ── Results Summary (Pronunciation Coach — Screen 9) ── */

export type PronunciationCategory = "Claridad" | "Ritmo" | "Entonación";

/** Extended WordFeedback with category for the pronunciation coach */
export interface PronunciationNote {
  word: string;
  phonetic: string;
  tip: string;
  category: PronunciationCategory;
}

/** Personalized area description (one per fixed category) */
export interface ImprovementArea {
  category: PronunciationCategory;
  description: string;
}

/**
 * Full results summary returned by the Edge Function.
 * Combines Gemini output (overallSentiment, pronunciationNotes, improvementAreas)
 * with computed fields (totalPhrases, totalTime) from session metadata.
 */
export interface ResultsSummary {
  /** Number of shadowing phrases practiced (computed by Edge Function) */
  totalPhrases: number;
  /** Session duration string (computed by Edge Function) */
  totalTime: string;
  /** Motivational summary line generated by Gemini */
  overallSentiment: string;
  /** 3-6 deduplicated pronunciation tips generated by Gemini */
  pronunciationNotes: PronunciationNote[];
  /** EXACTLY 3 areas — one per PronunciationCategory — personalized by Gemini */
  improvementAreas: ImprovementArea[];
}

/* ── Shadowing ── */

export interface ShadowingPhrase {
  /** Raw text with **stress** markers */
  text: string;
  feedback: WordFeedback;
  /** Scores per attempt (mock: hardcoded progression) */
  scores: number[];
}

/* ── Spaced Repetition ── */

export interface SRCard {
  id: string;
  phrase: string;
  word: string;
  phonetic: string;
  lastScore: number;
  intervalStep: number;
  origin: string;
  nextReviewDate?: string;
}

export interface SRInterval {
  step: number;
  days: number;
  label: string;
}

export interface SRSessionResult {
  cardId: string;
  score: number;
  passed: boolean;
  nextInterval: string;
}

/* ── Payment ── */

/** MVP pay-per-session credit packs */
export type CreditPack = "session_1" | "session_3" | "session_5";

export const CREDIT_PACK_DETAILS: Record<CreditPack, { sessions: number; price: number; perSession: number; discount: number }> = {
  session_1: { sessions: 1, price: 4.99, perSession: 4.99, discount: 0 },
  session_3: { sessions: 3, price: 12.99, perSession: 4.33, discount: 13 },
  session_5: { sessions: 5, price: 19.99, perSession: 4.00, discount: 20 },
};

export interface CheckoutResult {
  checkoutUrl: string;
  checkoutId: string;
}

export interface SubscriptionInfo {
  plan: UserPlan;
  status: "active" | "cancelled" | "past_due" | "none";
  currentPeriodEnd?: string;
  /** Number of session credits remaining (pay-per-session model) */
  creditsRemaining: number;
}

/* ── Practice History (Dashboard) ── */

export interface PracticeHistoryItem {
  title: string;
  date: string;
  duration: string;
  tag: string;
  /** Arena phase reached during the session */
  arenaPhaseReached?: ArenaPhase;
  /** Number of Power Phrases used/clicked during Arena */
  powerPhrasesUsed?: number;
  /** SR cards from this session still pending review */
  srCardsPending?: number;
  /** SR cards from this session already mastered */
  srCardsMastered?: number;
  /** One Before/After highlight from this session */
  beforeAfterHighlight?: BeforeAfterComparison;
}

/* ── Power Phrases ── */

export interface PowerPhrase {
  phrase: string;
  category: string;
  whenToUse: string;
  situation: string;
  accentColor: string;
}

/* ── Completed Phrase Summary (practice results) ── */

export interface CompletedPhraseSummary {
  num: number;
  text: string;
  highlight: { word: string; phonetic: string } | null;
  suffix: string;
  hasActions: boolean;
}

/* ── Arena / Progressive Scaffolding ── */

export type ArenaPhase = "support" | "guidance" | "challenge";

export interface ArenaPowerPhrase {
  id: string;
  phrase: string;
  context: string;
  category: "opener" | "transition" | "closing" | "objection" | "data" | "recast";
}

export interface ArenaState {
  phase: ArenaPhase;
  goodInteractions: number;
  totalInteractions: number;
  cognitiveLoadLevel: "normal" | "elevated";
}

/* ── Onboarding Profile ── */

export interface OnboardingProfile {
  industry: string;
  position: string;
  seniority: string;
}

/* ── Before/After Comparison (Briefing Room) ── */

export interface BeforeAfterComparison {
  userOriginal: string;
  professionalVersion: string;
  technique: string;
}