/**
 * ══════════════════════════════════════════════════════════════
 *  inFluentia PRO — Service Layer: Shared Types
 *  Models used across all service interfaces and adapters.
 * ══════════════════════════════════════════════════════════════
 */

/* ── User & Auth ── */

import type { UserPlan, User, AuthProvider } from "@/entities/user";
export type { UserPlan, User, AuthProvider };

/* ── Scenario Types (Master Prompt Adaptation) ── */

import type { ScenarioType, ChatMessage, SessionConfig, ArenaPhase, ArenaPowerPhrase, ArenaState } from "@/entities/session";
export type { ScenarioType, ChatMessage, SessionConfig, ArenaPhase, ArenaPowerPhrase, ArenaState };

/* ── Session & Conversation ── */

export interface PreparedSession {
  sessionId: string;
  systemPrompt: string;
  firstMessage: ChatMessage;
  /** ElevenLabs voice_id assigned by prepare-session based on interlocutor */
  voiceId?: string;
}

export interface ConversationTurnResult {
  /** AI's response message */
  aiMessage: ChatMessage;
  /** Whether the conversation has naturally concluded */
  isComplete: boolean;
  /** Contextual coaching hint generated by GPT-4o for the "Try saying" UI */
  coachingHint?: { starter: string; keywords?: string[]; strategy: string } | null;
}

/* ── Feedback ── */

export interface Strength {
  title: string;
  desc: string;
}

export interface Opportunity {
  title: string;
  tag?: string;
  desc: string;
}

export interface SessionFeedbackResult {
  strengths: Strength[];
  opportunities: Opportunity[];
  duration: string;
  scenarioType: string;
  
  // Extended AI Fields from /analyze-feedback
  beforeAfter?: BeforeAfterComparison[];
  pillarScores?: Record<string, number>;
  professionalProficiency?: number;
  contentScores?: ContentQualityScores;
  interviewReadinessScore?: number;
  preparationUtilization?: {
    score: number;
    verdict: string;
    insights: Array<{
      aspect: string;
      observation: string;
      rating: "strong" | "partial" | "missed";
    }>;
  };
  contentInsights?: ContentInsight[];
}

/* ── Improved Script ── */

export interface ScriptHighlight {
  phrase: string;
  color: string;
  tooltip: string;
}

export interface ScriptParagraph {
  text: string;
  highlights: ScriptHighlight[];
  suffix?: string;
  isHighlightBlock?: boolean;
}

export interface ScriptSection {
  num: number;
  title: string;
  paragraphs: ScriptParagraph[];
}

export interface ImprovedScriptResult {
  sections: ScriptSection[];
  estimatedReadTime: string;
}

/* ── Interview Briefing (card-per-question format) ── */

export interface InterviewQuestionCard {
  id: number;
  question: string;
  why: string;
  approach: string;
  suggestedOpener: string;
  framework?: { name: string; description: string };
  keyPhrases: ScriptHighlight[];
  pivot: string;
}

export interface InterviewQuestionToAsk {
  question: string;
  why: string;
}

export interface InterviewCulturalTip {
  title: string;
  description: string;
  type: "do" | "avoid";
}

export interface InterviewBriefingData {
  anticipatedQuestions: InterviewQuestionCard[];
  questionsToAsk: InterviewQuestionToAsk[];
  culturalTips: InterviewCulturalTip[];
}

/* ── Content Quality Scoring (Interview scenarios only) ── */

/** Content Quality dimensions evaluated for interview responses */
export interface ContentQualityScores {
  /** Did answers address what was actually asked? (0-100) */
  Relevance: number;
  /** Did they use STAR or other frameworks? (0-100) */
  Structure: number;
  /** Did they provide concrete examples and data? (0-100) */
  Examples: number;
  /** Were answers memorable and persuasive? (0-100) */
  Impact: number;
}

/** Combined interview readiness assessment */
export interface InterviewReadinessData {
  /** Content Quality scores (interview-specific axis) */
  contentScores: ContentQualityScores;
  /** Combined Interview Readiness Score (0-100) */
  interviewReadinessScore: number;
  /** Per-content-dimension feedback snippets */
  contentInsights?: ContentInsight[];
}

/** Short coaching insight per content dimension */
export interface ContentInsight {
  dimension: keyof ContentQualityScores;
  observation: string;
  tip: string;
}

/* ── Speech & Pronunciation ── */

export interface TranscriptionResult {
  text: string;
  confidence: number;
}

export interface WordFeedback {
  word: string;
  phonetic: string;
  tip: string;
}

export interface PronunciationResult {
  score: number;
  wordFeedback: WordFeedback;
}

/* ── Azure Pronunciation Assessment (detailed per-turn data) ── */

/** Phoneme-level assessment from Azure Speech */
export interface AzurePhonemeAssessment {
  phoneme: string;
  accuracyScore: number;
}

/** Word-level assessment from Azure Speech */
export interface AzureWordAssessment {
  word: string;
  accuracyScore: number;
  errorType: 'None' | 'Mispronunciation' | 'Omission' | 'Insertion';
  phonemes: AzurePhonemeAssessment[];
}

/** Full pronunciation assessment result for a single user turn */
export interface AzurePronunciationAssessment {
  /** Overall accuracy: did they pronounce each sound correctly? (0-100) */
  accuracyScore: number;
  /** Overall fluency: natural rhythm, no excessive pauses? (0-100) */
  fluencyScore: number;
  /** Completeness: did they say all the words? (0-100) */
  completenessScore: number;
  /** Prosody: natural intonation, stress patterns? (0-100) */
  prosodyScore: number;
  /** Combined pronunciation score (0-100) */
  pronScore: number;
  /** Word-level detail with phoneme breakdown */
  words: AzureWordAssessment[];
  /** Azure's own recognized text */
  recognizedText: string;
  /** Summary stats */
  wordCount: number;
  problemWordCount: number;
}

/** Pronunciation data accumulated across all turns in a session */
export interface SessionPronunciationData {
  /** Assessment per user turn (index = turn number) */
  turns: TurnPronunciationData[];
  /** Aggregated session-level scores (averages) */
  sessionAccuracy: number;
  sessionFluency: number;
  sessionProsody: number;
}

/** Pronunciation data for a single turn */
export interface TurnPronunciationData {
  turnIndex: number;
  assessment: AzurePronunciationAssessment;
  /** Timestamp when this turn was assessed */
  timestamp: string;
}

/** A practice phrase identified from poorly-scored words across the session */
export interface PracticePhrase {
  id: string;
  /** Full phrase (3-8 words) from the conversation */
  phrase: string;
  /** Professional context: why this phrase matters */
  context: string;
  /** Average score across words in the phrase */
  overallScore: number;
  /** Words within the phrase that were problematic */
  problemWords: {
    word: string;
    score: number;
    /** Human-readable mistake description */
    commonMistake: string;
  }[];
}

/** Fluency insight connecting pauses to specific vocabulary */
export interface FluencyInsight {
  /** Words per minute */
  speechRate: number;
  /** Target WPM for professional English */
  targetRate: [number, number]; // [min, max]
  /** Number of hesitation pauses detected */
  hesitationPauses: number;
  /** Words/phrases that caused hesitation */
  hesitationTriggers: string[];
  /** Actionable tip based on the data */
  tip: string;
}

/** Entry in the longitudinal Professional Vocabulary Tracker */
export interface VocabPronunciationEntry {
  word: string;
  category: 'Technical' | 'Business' | 'Leadership' | 'Communication';
  totalAttempts: number;
  scores: number[];
  currentScore: number;
  trend: 'improving' | 'stable' | 'declining';
  mastery: 'learning' | 'practicing' | 'mastered';
  commonError?: string;
  lastPracticed: string;
}

/* ── Results Summary (Pronunciation Coach — Screen 9) ── */

export type PronunciationCategory = "Claridad" | "Ritmo" | "Entonación";

/** Extended WordFeedback with category for the pronunciation coach */
export interface PronunciationNote {
  word: string;
  phonetic: string;
  tip: string;
  category: PronunciationCategory;
}

/** Personalized area description (one per fixed category) */
export interface ImprovementArea {
  category: PronunciationCategory;
  description: string;
}

/**
 * Full results summary returned by the Edge Function.
 * Combines Gemini output (overallSentiment, pronunciationNotes, improvementAreas)
 * with computed fields (totalPhrases, totalTime) from session metadata.
 */
export interface ResultsSummary {
  /** Number of shadowing phrases practiced (computed by Edge Function) */
  totalPhrases: number;
  /** Session duration string (computed by Edge Function) */
  totalTime: string;
  /** Motivational summary line generated by Gemini */
  overallSentiment: string;
  /** 3-6 deduplicated pronunciation tips generated by Gemini */
  pronunciationNotes: PronunciationNote[];
  /** EXACTLY 3 areas — one per PronunciationCategory — personalized by Gemini */
  improvementAreas: ImprovementArea[];
}

/* ── Session Summary (from /generate-summary endpoint) ── */

import type { SessionSummaryNextStep, SessionSummary } from "@/entities/feedback";
export type { SessionSummaryNextStep, SessionSummary };

/* ── Shadowing ── */

export interface ShadowingPhrase {
  /** Raw text with **stress** markers */
  text: string;
  feedback: WordFeedback;
  /** Scores per attempt (mock: hardcoded progression) */
  scores: number[];
}

/* ── Spaced Repetition ── */

export interface SRCard {
  id: string;
  phrase: string;
  word: string;
  phonetic: string;
  lastScore: number;
  intervalStep: number;
  origin: string;
  nextReviewDate?: string;
}

export interface SRInterval {
  step: number;
  days: number;
  label: string;
}

export interface SRSessionResult {
  cardId: string;
  score: number;
  passed: boolean;
  nextInterval: string;
}

/* ── Payment — Learning Path model (v9.0) ── */

/** v9.0: Purchase types for Learning Path model */
export type PurchaseType = "single_path" | "all_access" | "booster";

/** Learning Path product catalog */
export const PATH_PRODUCTS = {
  single_path: {
    type: "single_path" as PurchaseType,
    price: 24.99,
    label: "Learning Path",
    perSession: 2.08,
    sessionsIncluded: 12,
    description: "4 levels × 3 sessions + unlimited review",
  },
  all_access: {
    type: "all_access" as PurchaseType,
    price: 59.99,
    label: "All-Access Bundle",
    perPath: 12.00,
    pathsIncluded: 5,
    description: "All 5 Learning Paths — permanent access",
  },
  booster: {
    type: "booster" as PurchaseType,
    price: 4.99,
    label: "Booster Pack",
    sessionsIncluded: 3,
    description: "+3 fresh sessions for any level",
  },
} as const;

/** Details for creating a checkout */
export interface PurchaseDetails {
  type: PurchaseType;
  /** ScenarioType — required for single_path, optional for all_access */
  scenarioType?: string;
  /** Level to boost — required for booster */
  levelId?: string;
}

export interface CheckoutResult {
  checkoutUrl: string;
  checkoutId: string;
}

/** v9.0 replaces SubscriptionInfo — represents the user's path access state */
export interface PathAccessInfo {
  plan: UserPlan;
  /** Paths the user has purchased (ScenarioType[]) */
  pathsPurchased: string[];
  /** Whether user has all-access bundle */
  hasAllAccess: boolean;
}

/** Progress tracking for a single level within a path */
export interface PathLevelProgress {
  scenarioType: string;
  levelId: string;
  /** Fresh attempts consumed (max 3) */
  freshAttempts: number;
  /** Best session ID for review mode */
  bestSessionId: string | null;
  status: "locked" | "unlocked" | "completed";
  completedAt: string | null;
}

/** Dashboard status for a scenario's Learning Path */
export type PathStatus =
  | "not-started"
  | "demo-completed"
  | "purchased"
  | "in-progress"
  | "completed";

/** Access info for a specific level (computed from PathLevelProgress) */
export interface PathLevelAccess {
  scenarioType: string;
  levelId: string;
  freshAttempts: number;
  freshAttemptsRemaining: number;
  bestSessionId: string | null;
  status: "locked" | "unlocked" | "completed";
}

// ── Deprecated v7.0 types (kept temporarily for backward compat) ──
/** @deprecated v9.0 — use PurchaseType instead */
export type CreditPack = "session_1" | "session_3" | "session_5";
/** @deprecated v9.0 — use PATH_PRODUCTS instead */
export const CREDIT_PACK_DETAILS: Record<CreditPack, { sessions: number; price: number; perSession: number; discount: number }> = {
  session_1: { sessions: 1, price: 4.99, perSession: 4.99, discount: 0 },
  session_3: { sessions: 3, price: 12.99, perSession: 4.33, discount: 13 },
  session_5: { sessions: 5, price: 19.99, perSession: 4.00, discount: 20 },
};
/** @deprecated v9.0 — use PathAccessInfo instead */
export interface SubscriptionInfo {
  plan: UserPlan;
  status: "active" | "cancelled" | "past_due" | "none";
  currentPeriodEnd?: string;
  creditsRemaining: number;
}

/* ── Practice History (Dashboard) ── */

export interface PracticeHistoryItem {
  title: string;
  date: string;
  duration: string;
  tag: string;
  /** Arena phase reached during the session */
  arenaPhaseReached?: ArenaPhase;
  /** Number of Power Phrases used/clicked during Arena */
  powerPhrasesUsed?: number;
  /** SR cards from this session still pending review */
  srCardsPending?: number;
  /** SR cards from this session already mastered */
  srCardsMastered?: number;
  /** One Before/After highlight from this session */
  beforeAfterHighlight?: BeforeAfterComparison;
}

/* ── Power Phrases ── */

export interface PowerPhrase {
  phrase: string;
  category: string;
  whenToUse: string;
  situation: string;
  accentColor: string;
}

/* ── Completed Phrase Summary (practice results) ── */

export interface CompletedPhraseSummary {
  num: number;
  text: string;
  highlight: { word: string; phonetic: string } | null;
  suffix: string;
  hasActions: boolean;
}

/* ── Arena / Progressive Scaffolding — re-exported from @/entities/session ── */

/* ── Onboarding Profile ── */

import type { OnboardingProfile } from "@/entities/user";
export type { OnboardingProfile };

/* ── Before/After Comparison (Briefing Room) ── */

export interface BeforeAfterComparison {
  userOriginal: string;
  professionalVersion: string;
  technique: string;
}

/* ── Scenario Progression Tree ── */

export type LevelStatus = "locked" | "unlocked" | "study" | "completed";

export interface LevelState {
  status: LevelStatus;
  bestScore?: number;
  attempts?: number;
  remedialCompleted?: boolean;
}

export interface ProgressionState {
  activeGoal: ScenarioType;
  interview: Record<string, LevelState>;
  sales: Record<string, LevelState>;
}

export interface RemedialLesson {
  id: string;
  title: string;
  pillar: string;
  content: string;
  example: { wrong: string; correct: string };
}

export interface RemedialShadowingPhrase {
  id: string;
  phrase: string;
  focus: string;
}

export interface RemedialContent {
  generatedAt: string;
  weakPillars: string[];
  lessons: RemedialLesson[];
  shadowingPhrases: RemedialShadowingPhrase[];
  completedAt: string | null;
  shadowingScore: number | null;
}

/* ── Structured Lesson (5-step study phase) ── */

export interface LessonConceptStep {
  id: "concept";
  title: string;
  subtitle: string;
  body: string;
  mentalModel: string;
}

export interface LessonScenarioStep {
  id: "scenario";
  title: string;
  context: string;
  challenge: string;
}

export interface LessonComparisonStep {
  id: "comparison";
  title: string;
  weak: { label: string; script: string };
  strong: { label: string; script: string };
  analysis: string;
}

export interface LessonToolkitPhrase {
  pattern: string;
  usage: string;
}

export interface LessonToolkitStep {
  id: "toolkit";
  title: string;
  phrases: LessonToolkitPhrase[];
}

export interface LessonExerciseStep {
  id: "exercise";
  title: string;
  instruction: string;
  template: string;
  evaluationCriteria: string;
}

export type LessonStep =
  | LessonConceptStep
  | LessonScenarioStep
  | LessonComparisonStep
  | LessonToolkitStep
  | LessonExerciseStep;

export interface StructuredLesson {
  lessonTitle: string;
  targetPillar: string;
  nextLevelPrep: string;
  steps: LessonStep[];
  generatedAt: string;
  completedAt: string | null;
}