/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_4e8a5b39 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/dnbbkpwcpnoivguakvto/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e8a5b39").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Set with TTL — stores value wrapped in { _data, _expiresAt } envelope.
// TTL is in seconds. get() auto-detects and evicts expired entries.
export const setWithTTL = async (key: string, value: any, ttlSeconds: number): Promise<void> => {
  const envelope = {
    _data: value,
    _expiresAt: Date.now() + ttlSeconds * 1000,
  };
  await set(key, envelope);
};

// Get retrieves a key-value pair from the database.
// Auto-detects double-serialized values (string JSON inside JSONB) for backward compatibility.
// Auto-evicts expired TTL entries and returns null.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_4e8a5b39").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  let val = data?.value;
  // Backward compat: if value is a string that looks like JSON, auto-parse it
  if (typeof val === "string") {
    try {
      val = JSON.parse(val);
    } catch {
      return val;
    }
  }
  // TTL envelope detection: auto-evict expired entries
  if (val && typeof val === "object" && "_expiresAt" in val && "_data" in val) {
    if (Date.now() > val._expiresAt) {
      // Expired — delete in background, return null
      del(key).catch(() => {});
      return null;
    }
    return val._data;
  }
  return val;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e8a5b39").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e8a5b39").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
// Returns values in the SAME ORDER as the input keys array.
// Missing keys return null in their position.
export const mget = async (keys: string[]): Promise<any[]> => {
  if (keys.length === 0) return [];
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_4e8a5b39").select("key, value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  // Build a map for O(1) lookup, then return in original key order
  const map = new Map<string, any>();
  for (const d of data ?? []) {
    let val = d.value;
    // Backward compat: auto-parse double-serialized strings
    if (typeof val === "string") {
      try { val = JSON.parse(val); } catch { /* keep as string */ }
    }
    // TTL check
    if (val && typeof val === "object" && "_expiresAt" in val && "_data" in val) {
      if (Date.now() > val._expiresAt) {
        del(d.key).catch(() => {});
        continue; // skip expired — will return null
      }
      val = val._data;
    }
    map.set(d.key, val);
  }
  return keys.map(k => map.get(k) ?? null);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e8a5b39").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_4e8a5b39").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

/* ═══════════════════════════════════════════════════════════
   TTL Cleanup — delete expired entries in bulk.
   Call periodically (e.g., from an admin endpoint or cron).
   ═══════════════════════════════════════════════════════════ */
export const cleanupExpired = async (): Promise<number> => {
  const supabase = client();
  // Find all keys with TTL envelope where _expiresAt < now
  // Since JSONB queries support arrow operators:
  const { data, error } = await supabase
    .from("kv_store_4e8a5b39")
    .select("key, value")
    .not("value->_expiresAt", "is", null);

  if (error) {
    console.error("[KV Cleanup] Query error:", error.message);
    return 0;
  }

  const now = Date.now();
  const expiredKeys = (data ?? [])
    .filter((d: any) => {
      const exp = d.value?._expiresAt;
      return typeof exp === "number" && now > exp;
    })
    .map((d: any) => d.key);

  if (expiredKeys.length > 0) {
    await mdel(expiredKeys);
    console.log(`[KV Cleanup] Deleted ${expiredKeys.length} expired entries`);
  }

  return expiredKeys.length;
};

/* ═══════════════════════════════════════════════════════════
   Rate Limiter — in-memory token bucket per key.
   Designed for Edge Function request gating (per-user).
   
   Usage:
     const limiter = createRateLimiter({ maxTokens: 10, refillPerSecond: 1 });
     if (!limiter.allow(userId)) return c.json({ error: "Rate limited" }, 429);
   ═══════════════════════════════════════════════════════════ */
interface RateLimiterOptions {
  maxTokens: number;      // Max burst capacity
  refillPerSecond: number; // Tokens added per second
}

interface Bucket {
  tokens: number;
  lastRefill: number;
}

export function createRateLimiter(opts: RateLimiterOptions) {
  const buckets = new Map<string, Bucket>();

  return {
    allow(key: string): boolean {
      const now = Date.now();
      let bucket = buckets.get(key);

      if (!bucket) {
        bucket = { tokens: opts.maxTokens, lastRefill: now };
        buckets.set(key, bucket);
      }

      // Refill tokens based on elapsed time
      const elapsed = (now - bucket.lastRefill) / 1000;
      bucket.tokens = Math.min(opts.maxTokens, bucket.tokens + elapsed * opts.refillPerSecond);
      bucket.lastRefill = now;

      if (bucket.tokens >= 1) {
        bucket.tokens -= 1;
        return true;
      }

      return false;
    },

    // Cleanup stale buckets (call periodically)
    prune(maxAgeMs = 300_000): void {
      const now = Date.now();
      for (const [key, bucket] of buckets) {
        if (now - bucket.lastRefill > maxAgeMs) {
          buckets.delete(key);
        }
      }
    },
  };
}