/**
 * Mock data for MindsetPulse Coach responses.
 *
 * After the user completes the 3-step MindsetPulse questionnaire,
 * the coach compares their subjective perception against actual
 * session performance data and returns personalized micro-coaching.
 *
 * In production this would be generated by Gemini; here we use
 * deterministic mock data keyed by scenario.
 */
import type { ScenarioType } from "../../../types";

/* ── Objective session performance (what the AI measured) ── */

export interface SessionPerformanceMetrics {
  /** 0-100 overall score */
  overallScore: number;
  /** 0-100 how clear/understandable was the user */
  clarityScore: number;
  /** 0-100 grammar accuracy */
  grammarScore: number;
  /** 0-100 conversational fluency */
  fluencyScore: number;
  /** 0-100 strategic framing (did they use the right frameworks) */
  strategyScore: number;
  /** Key positive moment from the session */
  peakMoment: string;
  /** Brief description of the session in one line */
  sessionSummary: string;
}

const METRICS_BY_SCENARIO: Record<string, SessionPerformanceMetrics> = {
  sales: {
    overallScore: 74,
    clarityScore: 78,
    grammarScore: 68,
    fluencyScore: 71,
    strategyScore: 79,
    peakMoment:
      "When you reframed the pricing objection as ROI — that's exactly what a senior AE does.",
    sessionSummary:
      "Solid pitch with strong objection handling. Grammar had a few hiccups but clarity was consistent.",
  },
  interview: {
    overallScore: 71,
    clarityScore: 75,
    grammarScore: 72,
    fluencyScore: 66,
    strategyScore: 73,
    peakMoment:
      "Your STAR response about the cross-functional project was specific and compelling.",
    sessionSummary:
      "Well-structured answers with genuine motivation. Fluency dipped slightly on follow-up questions.",
  },
  csuite: {
    overallScore: 68,
    clarityScore: 72,
    grammarScore: 65,
    fluencyScore: 63,
    strategyScore: 76,
    peakMoment:
      "Opening with the recommendation before the data — that's executive communication.",
    sessionSummary:
      "Strategic framing was strong. Grammar and fluency need more practice for the C-suite pace.",
  },
  negotiation: {
    overallScore: 76,
    clarityScore: 80,
    grammarScore: 70,
    fluencyScore: 74,
    strategyScore: 81,
    peakMoment:
      "Your conditional concession — 'If you commit to annual, we can include onboarding' — was textbook.",
    sessionSummary:
      "Excellent strategic instincts. Value-based anchoring was natural. Minor grammar gaps under pressure.",
  },
  networking: {
    overallScore: 72,
    clarityScore: 77,
    grammarScore: 73,
    fluencyScore: 69,
    strategyScore: 70,
    peakMoment:
      "Asking about their challenge before pitching yourself — that's how you build real connections.",
    sessionSummary:
      "Warm and genuine delivery. Good at finding common ground. Could tighten the personal pitch.",
  },
};

/* ── Fear-specific coaching messages ── */

interface FearCoaching {
  /** Short validating headline */
  validation: string;
  /** Evidence-based reassurance using session data */
  insight: string;
  /** Practical micro-action for next time */
  action: string;
}

const FEAR_COACHING: Record<string, FearCoaching> = {
  blank: {
    validation: "El miedo a quedarte en blanco es universal — incluso CEOs lo sienten.",
    insight:
      "En tu sesión, mantuviste el hilo conversacional sin pausas prolongadas. Tu cerebro sabe más inglés del que crees — el estrés simplemente bloquea el acceso.",
    action:
      "Próxima sesión: cuando sientas el bloqueo, usa 'That's a great point — let me think about that for a moment.' Te da 5 segundos sin perder autoridad.",
  },
  grammar: {
    validation: "Preocuparte por la gramática demuestra que te importa la precisión.",
    insight:
      "Dato clave: tus errores gramaticales no afectaron la comprensión. El 94% de ejecutivos nativos priorizan claridad sobre gramática perfecta.",
    action:
      "Enfócate en 3 estructuras que ya dominas y úsalas como base. La perfección gramatical vendrá con la repetición, no con la preocupación.",
  },
  accent: {
    validation: "Tu acento es tu historia profesional — no es algo que 'arreglar'.",
    insight:
      "Tu clarity score fue {clarityScore}%. Eso significa que tu mensaje llegó con fuerza. Los acentos internacionales son la norma en negocios globales, no la excepción.",
    action:
      "En vez de suavizar tu acento, trabaja en la entonación de frases clave. Un 'I recommend we...' con la entonación correcta tiene más impacto que un acento perfecto.",
  },
  vocabulary: {
    validation: "Buscar la palabra exacta es señal de pensamiento sofisticado.",
    insight:
      "Tu sesión mostró que cuando usaste frases del Power Phrase Bank, tu fluidez subió notablemente. No necesitas más vocabulario — necesitas más confianza en el que ya tienes.",
    action:
      "Antes de tu próxima reunión real, revisa 5 frases del cheat sheet. Tenerlas 'precargadas' elimina la búsqueda en tiempo real.",
  },
  authority: {
    validation: "Querer sonar profesional es exactamente lo que te hace profesional.",
    insight:
      "Tu strategy score fue {strategyScore}% — eso significa que tus ideas y estructura estuvieron al nivel. La autoridad no viene del acento, viene del contenido y la estructura.",
    action:
      "Usa la técnica 'Conclusion First': abre con tu recomendación y luego da la evidencia. Esto proyecta autoridad instantánea independientemente del idioma.",
  },
  speed: {
    validation: "Sentir que la conversación va rápido es normal — tu cerebro procesa en dos idiomas.",
    insight:
      "Tu fluency score fue {fluencyScore}%. Mantuviste el ritmo de la conversación mejor de lo que percibes. El desafío no es tu velocidad — es tu percepción de ella.",
    action:
      "Practica 'strategic pausing': una pausa de 2 segundos antes de responder no te hace lento — te hace reflexivo. Los ejecutivos senior lo hacen todo el tiempo.",
  },
  none: {
    validation: "No identificar un miedo específico es una señal de fortaleza.",
    insight:
      "Tu sesión mostró un perfil equilibrado. Tu próximo nivel no es eliminar debilidades — es amplificar tus fortalezas naturales.",
    action:
      "En tu próxima sesión, elige un escenario que te incomode un poco más. El crecimiento está justo al borde de tu zona de confort.",
  },
};

/* ── Perception Gap coaching (Liking Gap) ── */

interface PerceptionGapInsight {
  /** Headline for the gap */
  headline: string;
  /** Explanatory paragraph */
  body: string;
  /** Name of the psychological concept */
  concept: string;
}

/**
 * Returns a perception gap insight based on the difference between
 * self-assessment (1-5) and actual performance (0-100).
 *
 * The "normalized self" maps 1-5 to roughly 20-100:
 *   1→20, 2→40, 3→60, 4→80, 5→100
 */
function getPerceptionGap(
  selfAssessment: number,
  actualScore: number
): PerceptionGapInsight {
  const normalizedSelf = selfAssessment * 20;
  const gap = actualScore - normalizedSelf;

  if (gap >= 15) {
    // User underestimates themselves significantly
    return {
      headline: "Te subestimas — y eso es completamente normal",
      body: `Tu auto-evaluación fue ${selfAssessment}/5, pero tu desempeño real fue ${actualScore}/100. Esta brecha se llama el "Liking Gap": las personas consistentemente creen que su impacto fue menor de lo que realmente fue. En tu caso, la diferencia es de ${gap} puntos. Tu próximo objetivo no es mejorar tu inglés — es confiar en el que ya tienes.`,
      concept: "Liking Gap",
    };
  } else if (gap >= 5) {
    // Slight underestimation
    return {
      headline: "Tu percepción está casi calibrada — con un ligero sesgo",
      body: `Evaluaste tu desempeño en ${selfAssessment}/5 y obtuviste ${actualScore}/100. Estás cerca, pero aún subestimas ligeramente tu capacidad. Esto es común en profesionales LATAM que operan en inglés — la exigencia cultural es alta. Reconoce que lo estás haciendo bien.`,
      concept: "Sesgo de autoexigencia",
    };
  } else if (gap >= -10) {
    // Well calibrated
    return {
      headline: "Tu autopercepción está bien calibrada",
      body: `Evaluaste tu desempeño en ${selfAssessment}/5 y obtuviste ${actualScore}/100. Esa alineación entre percepción y realidad es una fortaleza ejecutiva. Significa que puedes confiar en tu instinto para saber cuándo estás comunicando efectivamente.`,
      concept: "Metacognición precisa",
    };
  } else {
    // User overestimates
    return {
      headline: "Tu confianza supera tu ejecución actual — y eso tiene valor",
      body: `Evaluaste tu desempeño en ${selfAssessment}/5 pero obtuviste ${actualScore}/100. Esa confianza es un activo — úsala como combustible para practicar las áreas técnicas. Las personas seguras que además son precisas son imparables.`,
      concept: "Confianza como catalizador",
    };
  }
}

/* ── Confidence-specific nudge ── */

function getConfidenceNudge(
  confidenceLevel: number,
  actualScore: number
): string {
  if (confidenceLevel <= 2 && actualScore >= 65) {
    return "Sentiste inseguridad, pero tu desempeño dice otra cosa. Esa brecha entre cómo te sientes y cómo te perciben es exactamente lo que el Liking Gap predice. Con cada sesión, esa brecha se cierra.";
  }
  if (confidenceLevel <= 2 && actualScore < 65) {
    return "Es normal sentir inseguridad cuando estás construyendo una nueva habilidad. Lo importante: completaste la sesión. Cada minuto de práctica está recableando tu cerebro para el inglés ejecutivo.";
  }
  if (confidenceLevel >= 4 && actualScore >= 75) {
    return "Tu confianza alta coincide con un desempeño sólido. Estás en el punto donde puedes empezar a tomar riesgos comunicativos — frases más complejas, opiniones más directas.";
  }
  if (confidenceLevel >= 4 && actualScore < 65) {
    return "Tu confianza es un activo enorme. Ahora canalízala hacia áreas específicas: gramática bajo presión y fluidez en respuestas espontáneas. La confianza + precisión es la combinación ganadora.";
  }
  // Middle confidence
  return "Un nivel de confianza moderado es saludable — significa que eres consciente de dónde estás y hacia dónde vas. Tu próxima sesión es una oportunidad de subir un punto.";
}

/* ── Public API ── */

export interface MindsetCoachingResponse {
  perceptionGap: PerceptionGapInsight;
  fearCoaching: FearCoaching;
  confidenceNudge: string;
  metrics: SessionPerformanceMetrics;
  /** A single takeaway sentence the user should remember */
  takeaway: string;
}

/**
 * Generates a personalized coaching response based on the user's
 * MindsetPulse answers and the session's objective metrics.
 */
export function generateMindsetCoaching(
  scenarioType: ScenarioType | undefined,
  pulse: {
    confidenceLevel: number;
    biggestFear: string;
    selfAssessment: number;
  }
): MindsetCoachingResponse {
  const scenario = scenarioType || "sales";
  const metrics =
    METRICS_BY_SCENARIO[scenario] || METRICS_BY_SCENARIO["sales"];

  const perceptionGap = getPerceptionGap(
    pulse.selfAssessment,
    metrics.overallScore
  );

  // Replace placeholders in fear coaching
  const rawFear = FEAR_COACHING[pulse.biggestFear] || FEAR_COACHING["none"];
  const fearCoaching: FearCoaching = {
    validation: rawFear.validation,
    insight: rawFear.insight
      .replace("{clarityScore}", String(metrics.clarityScore))
      .replace("{fluencyScore}", String(metrics.fluencyScore))
      .replace("{strategyScore}", String(metrics.strategyScore))
      .replace("{grammarScore}", String(metrics.grammarScore)),
    action: rawFear.action,
  };

  const confidenceNudge = getConfidenceNudge(
    pulse.confidenceLevel,
    metrics.overallScore
  );

  // Generate takeaway based on the biggest gap
  const takeaway = generateTakeaway(pulse, metrics);

  return {
    perceptionGap,
    fearCoaching,
    confidenceNudge,
    metrics,
    takeaway,
  };
}

function generateTakeaway(
  pulse: { confidenceLevel: number; biggestFear: string; selfAssessment: number },
  metrics: SessionPerformanceMetrics
): string {
  const normalizedSelf = pulse.selfAssessment * 20;
  const gap = metrics.overallScore - normalizedSelf;

  if (gap >= 15) {
    return "Tu inglés ejecutivo ya es más fuerte de lo que crees. La próxima vez que dudes, recuerda este número.";
  }
  if (pulse.confidenceLevel <= 2) {
    return "La inseguridad que sientes no es falta de habilidad — es falta de evidencia. Cada sesión te da más evidencia.";
  }
  if (metrics.overallScore >= 75) {
    return "Estás en el nivel donde los detalles marcan la diferencia. Enfócate en pulir, no en reconstruir.";
  }
  return "Cada sesión es un paso. No necesitas ser perfecto — necesitas ser consistente. Nos vemos mañana.";
}

/** Convenience: get metrics only (for components that need scores without coaching) */
export function getSessionMetricsForScenario(
  scenarioType: ScenarioType | undefined
): SessionPerformanceMetrics {
  const scenario = scenarioType || "sales";
  return METRICS_BY_SCENARIO[scenario] || METRICS_BY_SCENARIO["sales"];
}
