-- ══════════════════════════════════════════════════════════════
--  inFluentia PRO — Fase 1: Complete Database Migration
--
--  Execute this ENTIRE script in Supabase SQL Editor (single run).
--  It creates: 5 tables, 1 trigger, 5 RLS policy sets, 3 indexes.
--
--  Prerequisites:
--    1. Supabase project created
--    2. Google OAuth provider configured in Authentication > Providers
--    3. Redirect URL added: https://<your-domain>/auth/callback
--
--  Reference: MASTER_BLUEPRINT.md §3 (Architecture de Datos)
--  QA Tests:  F1-08 through F1-14
--
--  v2.1 Changes (sync with codebase):
--    - profiles.market_focus: Added 'brazil' to CHECK constraint
--    - profiles.plan: Simplified to MVP values ('free', 'per-session')
--    - sessions: Added scenario_type, arena_phase_reached columns
--    - sessions: Added mindset_pulse JSONB column
--    - sessions.scenario_config comment: Updated interlocutor values
--    - Removed all LinkedIn OAuth references (only Google remains)
--    - Updated comments to reflect Brazil market support
-- ══════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════
--  TABLE 1: profiles
--  Blueprint §3.1 — Auth & Metadata
--  Links 1:1 with auth.users via id FK
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.profiles (
  id               uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  market_focus     text CHECK (market_focus IN ('mexico', 'colombia', 'brazil')),
  plan             text DEFAULT 'free'
                     CHECK (plan IN ('free', 'per-session')),
  plan_status      text DEFAULT 'active'
                     CHECK (plan_status IN ('active', 'trial', 'expired')),
  free_session_used boolean DEFAULT false,
  stats            jsonb DEFAULT '{}'::jsonb,
    -- Cache: { "sessions_count": 0, "avg_score": 0, "power_phrases_count": 0 }
  achievements     text[] DEFAULT '{}',
    -- Misiones completadas: ["The 24-Hour Pulse", "Mirror Match", etc.]
  created_at       timestamptz DEFAULT now()
);

COMMENT ON TABLE  public.profiles IS 'User profile — 1:1 with auth.users. Contains plan, stats cache, achievements.';
COMMENT ON COLUMN public.profiles.stats IS 'JSON cache: sessions_count, avg_score, power_phrases_count. Updated by Edge Functions.';
COMMENT ON COLUMN public.profiles.market_focus IS 'mexico, colombia, or brazil — determines regional vocabulary in prompts and cultural directives in analyst.';

-- ═══════════════════════════════════════════════════════════
--  TABLE 2: sessions
--  Blueprint §3.2 — Practice sessions with conversation history
--  NOTE: history as JSONB is documented technical debt (-> V4.0)
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.sessions (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  scenario_config  jsonb NOT NULL,
    -- { "scenario": "...", "interlocutor": "client|manager|recruiter|peer",
    --   "scenarioType": "interview|sales", "market_focus": "mexico|colombia|brazil" }
  system_prompt    text,
    -- Full assembled prompt generated by Edge Function prepare-session
  voice_id         text,
    -- ElevenLabs voice_id assigned by prepare-session based on interlocutor
  scenario_type    text CHECK (scenario_type IN ('interview', 'sales')),
    -- MVP scenario types. Future: 'csuite', 'negotiation', 'networking'
    -- (adaptations exist in assembler.ts but UI doesn't expose them yet)
  history          jsonb DEFAULT '[]'::jsonb,
    -- Array of { role, content, audio_url, internal_analysis? }
    -- internal_analysis is BACKEND-ONLY — never sent to frontend
  feedback         jsonb,
    -- { strengths: [...], opportunities: [...], improved_script: {...} }
  arena_phase_reached text CHECK (arena_phase_reached IN ('support', 'guidance', 'challenge')),
    -- Highest arena phase the user reached during this session
    -- Maps to ArenaPhase type in types.ts
  mindset_pulse    jsonb,
    -- Post-session self-assessment: { confidenceLevel: 1-5, biggestFear: "...",
    --   selfAssessment: 1-5, completedAt: "ISO date" }
    -- Maps to MindsetPulseResult type in types.ts
  status           text DEFAULT 'active'
                     CHECK (status IN ('active', 'completed')),
  turn_count       int DEFAULT 0,
    -- Counter for isComplete logic (4-8 turn range)
  created_at       timestamptz DEFAULT now()
);

COMMENT ON TABLE  public.sessions IS 'Practice sessions. history JSONB is tech debt — migrate to session_messages in V4.0.';
COMMENT ON COLUMN public.sessions.history IS 'JSONB array. AI entries include internal_analysis (backend-only, never exposed to frontend).';
COMMENT ON COLUMN public.sessions.scenario_type IS 'MVP: interview|sales. Future types prepared in assembler.ts (csuite, negotiation, networking).';
COMMENT ON COLUMN public.sessions.arena_phase_reached IS 'Progressive scaffolding: support -> guidance -> challenge. Logged for practice history.';

-- ═══════════════════════════════════════════════════════════
--  TABLE 3: sr_cards (Spaced Repetition)
--  Blueprint §3.3 — Cards with 4-step interval system
--  Intervals: 24h -> 3d -> 7d -> 14d
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.sr_cards (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  session_id       uuid REFERENCES public.sessions(id) ON DELETE SET NULL,
    -- Source session that generated this card (nullable for manual adds)
  phrase           text NOT NULL,
  problem_word     text,
    -- The specific word that needs work (shown on card)
  phonetic         text,
    -- IPA phonetic transcription of the problem word
  interval_step    int DEFAULT 1
                     CHECK (interval_step BETWEEN 1 AND 4),
    -- 1=24h, 2=3d, 3=7d, 4=14d (graduated)
  next_review_at   timestamptz DEFAULT now(),
  last_score       int DEFAULT 0,
  created_at       timestamptz DEFAULT now()
);

COMMENT ON TABLE  public.sr_cards IS 'Spaced Repetition cards. interval_step 1-4 maps to 24h/3d/7d/14d review cycle.';

-- ═══════════════════════════════════════════════════════════
--  TABLE 4: power_phrases
--  Blueprint §3.4 — Saved phrases with category & context
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.power_phrases (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  phrase            text NOT NULL,
  category          text,
    -- "Negotiation", "Softening", "Closing", "Persuasion", etc.
  context_usage     text,
    -- When to use it (human-readable description)
  source_session_id uuid REFERENCES public.sessions(id) ON DELETE SET NULL,
  created_at        timestamptz DEFAULT now()
);

COMMENT ON TABLE public.power_phrases IS 'User-saved power phrases from practice sessions, with category and usage context.';

-- ═══════════════════════════════════════════════════════════
--  TABLE 5: audit_logs (Financial Control)
--  Blueprint §3.5 — Cost tracking for $12-$14 margin monitoring
--  Every Edge Function call logs here automatically
-- ═══════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  function_name    text NOT NULL,
    -- prepare-session, process-turn, analyze-feedback, generate-script,
    -- generate-results-summary, score-pronunciation, tts-generate
  user_id          uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  session_id       uuid REFERENCES public.sessions(id) ON DELETE SET NULL,
  tokens_in        int DEFAULT 0,
  tokens_out       int DEFAULT 0,
  elevenlabs_chars int DEFAULT 0,
    -- Characters sent to ElevenLabs TTS (for billing tracking)
  model            text,
    -- gpt-4o, gpt-4o-mini, gemini-1.5-flash, azure-tts, elevenlabs, etc.
  latency_ms       int DEFAULT 0,
  cost_estimated   numeric(10,4) DEFAULT 0,
    -- USD cost estimated by the Edge Function at call time
  error_code       text,
    -- NULL on success, error code on failure (for debugging)
  created_at       timestamptz DEFAULT now()
);

COMMENT ON TABLE  public.audit_logs IS 'Financial control — every AI/TTS call is logged with cost. Critical for $12-$14/user margin.';
COMMENT ON COLUMN public.audit_logs.cost_estimated IS 'USD estimated cost. Calculated in Edge Function using token counts * model pricing.';

-- ═══════════════════════════════════════════════════════════
--  INDEXES
--  Performance-critical queries identified from Dashboard & SR
-- ═══════════════════════════════════════════════════════════

-- Dashboard: "Get today's SR cards" query
CREATE INDEX IF NOT EXISTS idx_sr_cards_user_review
  ON public.sr_cards (user_id, next_review_at);

-- Dashboard: "Get practice history" query
CREATE INDEX IF NOT EXISTS idx_sessions_user_created
  ON public.sessions (user_id, created_at DESC);

-- Cost monitoring: "Total cost per user this month" query
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_created
  ON public.audit_logs (user_id, created_at);

-- ═══════════════════════════════════════════════════════════
--  TRIGGER: Auto-create profile on user registration
--  QA Test: F1-12
--
--  When auth.users gets a new row (Google OAuth),
--  this trigger automatically creates the profiles row
--  with default values. No manual INSERT needed.
-- ═══════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, market_focus, stats)
  VALUES (
    NEW.id,
    -- Default market_focus — can be updated later via onboarding or IP detection
    'mexico',
    -- Initialize stats cache with zeros
    '{"sessions_count": 0, "avg_score": 0, "power_phrases_count": 0}'::jsonb
  );
  RETURN NEW;
END;
$$;

-- Drop existing trigger if re-running migration
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ═══════════════════════════════════════════════════════════
--  ROW LEVEL SECURITY (RLS)
--  QA Tests: F1-10, F1-11
--
--  Principle: Every user can ONLY access their own data.
--  Service role (Edge Functions) bypasses RLS for admin ops.
-- ═══════════════════════════════════════════════════════════

-- --- profiles ---
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Note: INSERT is handled by the trigger (SECURITY DEFINER).
-- Users should NOT be able to INSERT profiles directly.
-- DELETE is intentionally omitted (account deletion via admin/support).

-- --- sessions ---
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own sessions"
  ON public.sessions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own sessions"
  ON public.sessions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions"
  ON public.sessions FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- --- sr_cards ---
ALTER TABLE public.sr_cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own SR cards"
  ON public.sr_cards FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own SR cards"
  ON public.sr_cards FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own SR cards"
  ON public.sr_cards FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- --- power_phrases ---
ALTER TABLE public.power_phrases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own power phrases"
  ON public.power_phrases FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own power phrases"
  ON public.power_phrases FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own power phrases"
  ON public.power_phrases FOR DELETE
  USING (auth.uid() = user_id);

-- --- audit_logs ---
-- Users can READ their own logs (for transparency).
-- Only Edge Functions (service role) can INSERT.
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own audit logs"
  ON public.audit_logs FOR SELECT
  USING (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE for regular users.
-- Edge Functions use service_role key which bypasses RLS.

-- ═══════════════════════════════════════════════════════════
--  MIGRATION PATCH (for existing databases)
--
--  If you already ran the v1.0 migration, execute ONLY this
--  section to bring your schema up to v2.1.
--  Skip this if running the full migration for the first time.
-- ═══════════════════════════════════════════════════════════

-- Patch 1: Add 'brazil' to profiles.market_focus CHECK
-- ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_market_focus_check;
-- ALTER TABLE public.profiles ADD CONSTRAINT profiles_market_focus_check
--   CHECK (market_focus IN ('mexico', 'colombia', 'brazil'));

-- Patch 2: Simplify profiles.plan CHECK to MVP values
-- ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_plan_check;
-- ALTER TABLE public.profiles ADD CONSTRAINT profiles_plan_check
--   CHECK (plan IN ('free', 'per-session'));

-- Patch 3: Add scenario_type column to sessions
-- ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS
--   scenario_type text CHECK (scenario_type IN ('interview', 'sales'));

-- Patch 4: Add arena_phase_reached column to sessions
-- ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS
--   arena_phase_reached text CHECK (arena_phase_reached IN ('support', 'guidance', 'challenge'));

-- Patch 5: Add mindset_pulse column to sessions
-- ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS
--   mindset_pulse jsonb;

-- Patch 6: Update market_focus comment
-- COMMENT ON COLUMN public.profiles.market_focus IS
--   'mexico, colombia, or brazil — determines regional vocabulary in prompts and cultural directives in analyst.';

-- ═══════════════════════════════════════════════════════════
--  VERIFICATION QUERIES
--  Run these after migration to confirm everything is correct.
--  Expected: all 5 tables exist, RLS enabled, trigger active.
-- ═══════════════════════════════════════════════════════════

-- Check tables exist:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND table_name IN ('profiles', 'sessions', 'sr_cards', 'power_phrases', 'audit_logs');

-- Check RLS is enabled:
-- SELECT tablename, rowsecurity FROM pg_tables
-- WHERE schemaname = 'public'
-- AND tablename IN ('profiles', 'sessions', 'sr_cards', 'power_phrases', 'audit_logs');

-- Check trigger exists:
-- SELECT trigger_name, event_manipulation, action_statement
-- FROM information_schema.triggers
-- WHERE trigger_name = 'on_auth_user_created';

-- Check new columns exist:
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_name = 'sessions'
-- AND column_name IN ('scenario_type', 'arena_phase_reached', 'mindset_pulse');
